apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-11-06T16:05:16Z"
  labels:
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "22"
  uid: 05f6d252-5051-42d2-81a0-8a539776ed4c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
