apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-11-06T16:05:16Z"
  labels:
    kubernetes.io/metadata.name: kube-public
  name: kube-public
  resourceVersion: "14"
  uid: 9d0b76cc-d88c-4924-b108-7b73401f153f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
