---
apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-deletion-protection
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: https://github.com/stevendborrelli/function-deletion-protection
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: A function that prevents deletion by creating Usages
spec:
  capabilities:
    - composition
    - operation
